[package]
name = "detection-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
rumqttc = "0.24"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "sync"] }
